name: dart_code_metrics
version: 4.0.0
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://github.com/dart-code-checker/dart-code-metrics
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.7.0
  analyzer_plugin: ^0.6.0
  ansicolor: ^2.0.1
  args: ^2.0.0
  collection: ^1.15.0
  crypto: ^3.0.0
  file: ^6.0.0
  glob: ^2.0.1
  html: ">=0.15.0 <1.0.0"
  meta: ^1.3.0
  path: ^1.8.0
  quiver: ^3.0.0
  source_span: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.2
  mocktail: ^0.1.1
  pedantic: ^1.11.0
  test: ^1.16.8

executables:
  metrics:
