name: metrics
description: Command line tool which helps to improve code quality
version: 1.1.0
homepage: https://github.com/wrike/metrics
author: Dmitry Krutskih <dmitry.krutskikh@team.wrike.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  analyzer: '>=0.38.0 <0.39.0'
  ansicolor: ^1.0.0
  args: ^1.5.0
  built_collection: ^4.2.0
  glob: ^1.2.0
  html: '>=0.13.0 < 1.0.0'
  intl: ^0.15.2
  meta: ^1.1.0
  path: ^1.6.0
  resource: ^2.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0

executables:
  metrics:
