name: dart_code_metrics
description: Software analytics tool that helps developers analyse and improve software quality.
version: 2.1.1
homepage: https://github.com/wrike/dart-code-metrics

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  analyzer: ^0.39.3
  analyzer_plugin: '>=0.2.1 <0.4.0'
  ansicolor: ^1.0.4
  args: ^1.4.4
  crypto: ^2.0.6
  glob: ^1.1.7
  html: '>=0.13.4 <1.0.0'
  meta: ^1.1.6
  path: ^1.6.2
  quiver: ^2.0.0
  source_span: ^1.4.1
  yaml: ^2.1.5

dev_dependencies:
  coverage: ^0.14.0
  coveralls: ^5.9.0
  dependency_validator: ^1.5.0
  lcov: '>=5.7.0 <7.0.0'
  mockito: ^4.1.1
  pedantic: ^1.9.2
  pub_semver: ^1.4.4
  test: ^1.15.3
  http_multi_server: ^2.2.0

executables:
  metrics:
