name: dart_code_metrics
version: 5.7.6
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: ">=2.18.0 <3.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ">=5.1.0 <5.14.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  ansicolor: ^2.0.1
  args: ^2.0.0
  collection: ^1.16.0
  crypto: ^3.0.0
  dart_code_metrics_presets: ^1.0.1
  file: ^6.0.0
  glob: ^2.0.1
  html: ">=0.15.0 <1.0.0"
  http: ^0.13.5
  meta: ^1.7.0
  path: ^1.8.0
  platform: ^3.1.0 # overridden for lowest versions compatibility
  pub_updater: ^0.3.0
  source_span: ^1.8.0
  uuid: ^3.0.7
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.2
  intl: ">=0.17.0 <0.19.0"
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
