name: dart_code_metrics
version: 4.17.0
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dartcodemetrics.dev
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dartcodemetrics.dev/docs/getting-started/introduction

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: ">=4.1.0 <4.5.0"
  analyzer_plugin: ">=0.11.0 <0.12.0"
  ansicolor: ^2.0.1
  args: ^2.0.0
  collection: ^1.15.0
  crypto: ^3.0.0
  file: ^6.0.0
  glob: ^2.0.1
  html: ">=0.15.0 <1.0.0"
  meta: ^1.7.0
  path: ^1.8.0
  source_span: ^1.8.0
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.2
  intl: ^0.17.0
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.21.0

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
