name: build

on: [push, pull_request]

jobs:
  build-dart-latest:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run dependency validator
      run: pub run dependency_validator --ignore coveralls,intl,http_multi_server
    - name: Run dartanalyzer
      run: dartanalyzer --fatal-warnings --fatal-infos --fatal-lints bin/ lib/ test/
    - name: Run dartfmt
      run: dartfmt --set-exit-if-changed -n .
    - name: Run tests
      env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
      if: success()
      run:  |
        pub run test --coverage=coverage
        pub run coverage:format_coverage --packages=.packages -i coverage -o coverage/coverage.lcov --lcov --report-on=lib
        pub run tool/format_coverage.dart
        pub run coveralls:coveralls coverage/coverage.lcov
    - name: Self scan
      run: dart bin/metrics.dart --reporter=github lib

  build-dart-2-8:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:2.8.4

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub downgrade
    - name: Run dartanalyzer
      run: dartanalyzer --fatal-warnings --fatal-infos --fatal-lints bin/ lib/ test/
    - name: Run tests
      run: pub run test
